### ISSUE TITLE
Allow re-use of existing parameters on Stack update

### ISSUE THREAD

**Issue by 1I1III1liL1** [fog/fog-openstack#264]
The OpenStack CLI has the `--existing` that lets template arguments to be omitted. From [the documentation](http://docs.openstack.org/cli-reference/heat.html):

> -x, --existing
Re-use the template, parameters and environment of the current stack. If the template argument is omitted then the existing template is used. If no --environment-file is specified then the existing environment is used. Parameters specified in --parameters will patch over the existing values in the current stack. Parameters omitted will keep the existing values.

Orchestration's `update_stack` method seems to mysteriously [not be documented](https://github.com/fog/fog-openstack/blob/master/docs/orchestration.md).
 
Calling `Orchestration`'s `update_stack` method with the stack and template updates without parameters specified in the has results in an `Excon::Error::BadRequest` because parameters are missing.

Is the ability to update a stack and use existing parameters missing in Fog, or did I not find it?

**Comment by gildub** [comment]
@1I1III1liL1, 

The method has two signatures. 

1. The first signature uses the Collection approach and accepts a Stack object (as Fog::Orchestraton::Openstack::Stack) and the data as expected in [1].

For example, assuming the service is create such as"  
```ruby
@orchest = Fog::Orchestration::OpenStack.new(<AUTHENTICATION DETAILS>)
``` 
Then the following works:
```ruby

heat_template = {
  "files": {},
  "disable_rollback": true,
  "stack_name": "test_stackx",
  "template": {
    "heat_template_version": "2013-05-23",
    "description": "Test Template x",
    "resources": {
      "private_test_network": {
        "type": "OS::Neutron::Net",
        "properties": { "name": "test_networkx" }
      }
    }
  },
  "timeout_mins": 60
}

response = @orchest.create_stack(heat_template)
id = response.body["stack"]["id"]

# Give time for stack creation to avoid conflit
`sleep 10`

stack = @orchest.stacks.get("test_stackx", id)

heat_template[:template][:description] = "Updated Test Template x"
@orchest.update_stack(stack, heat_template)

# Give time for stack update
`sleep 10`

p @orchest.stacks.get("test_stackx", id).description
```

2. The second signature, advertised as "deprecated", expects a stack name, a stack id and the template data only. 

- I believe it shouldn't be considered "deprecated" because the API [1] is "CURRENT" and some fog-openstack users might want to use only the request approach (as opposed to the Collection).  
- Also the signature is wrong because the stack name should be first, followed by the stack id.  
- Finally the third parameter should not be expected to be the template data details but the whole object as described in [1]. I should be exactly behaving as with `create_stack` method.

So I'm going to propose a patch to fix the second signature and remove the "deprecated" message. 

[1] https://developer.openstack.org/api-ref/orchestration/v1/?expanded=create-configuration-detail,update-stack-detail

**Comment by gildub** [comment]
Added examples in https://github.com/fog/fog-openstack/pull/277
