### ISSUE TITLE
OpenStack compute broken for nova URLs without project ID in 0.1.23

### ISSUE THREAD

**Issue by voelzmo** [fog/fog-openstack#356]
If the nova URL does not contain the project ID, and therefore ends with e.g. `/v2.1`, fog-openstack version 0.1.23 throws the following error:
```
OpenStack compute binding only supports version v2 and v2.1
```

Fixed by #347

**Comment by oblutak** [comment]
Do you mean broken or fixed by [#347](https://github.com/fog/fog-openstack/pull/347)

The error above seems to come from [this commit's logic](https://github.com/fog/fog-openstack/commit/7a9fdbc41d1283ca382c6c04d8162cf476bbd240#diff-a938d2d946106b58dccd9833beebfe6e). The change got picked by the release of 0.1.23, so to me the current release is broken.

In [this line of code](https://github.com/fog/fog-openstack/blob/a0dff17ba9a0054c665aa967a32be19506693269/lib/fog/openstack/core.rb#L199) of openstack/core.rb we appear to intentionally remove the trailing '/'.  but the [regex](https://github.com/fog/fog-openstack/blob/a0dff17ba9a0054c665aa967a32be19506693269/lib/fog/compute/openstack.rb#L399) of compute/openstack.rb tries to match the trailing '/'. 

Should it just match the end of string?  I'm pretty new to using openstack, so don't trust my opinion.  I'm just trying to report what I am seeing...

**Comment by voelzmo** [comment]
@oblutak correct analysis on your side: 
* commit https://github.com/fog/fog-openstack/commit/7a9fdbc41d1283ca382c6c04d8162cf476bbd240#diff-a938d2d946106b58dccd9833beebfe6e created this bug in release 0.1.23, because it matches only if a slash comes after the version number
* PR #347 fixes this

Unfortunately, there is a variety in terms of URLs to match. Some OpenStack installations have nova URLs looking like this `http://<URL>:8774/v2.1/3eaa54319ab445e19ddee963cf57df95`, i.e. they contain the project id at the end. Therefore, they work with 0.1.23 and that's what we used for validating our change, because all of our OpenStack installations seem to have URLs looking like this.
Other installations seem to have URLs without a project ID at the end, therefore they don't match anymore after the trailing slash is removed, e.g. `http://<URL>:8774/v2.1`.

**Comment by voelzmo** [comment]
ping @gildub @Ladas

**Comment by gildub** [comment]
@voelzmo, yeah OpenStack catalog has been changing. Anyway this is now closed. Thank you.
