### ISSUE TITLE
Need Ruby 2.0.0 support for fog-openstack.

### ISSUE THREAD

**Issue by sleepyorion** [fog/fog-openstack#384]
We have a large deployment of OpenStack using our PaaS layer (OneOps) that currently locked at Ruby 2.0.0 therefore we are unable upgrade to the latest version of fog-openstack as it required Ruby >= 2.1.  We need to use the latest version as the previous version 0.1.21 (current deployment) not able to communicate with our new OpenStack infrastructure using Pike.

We have forked the current version and relax the restriction to Ruby 2.0.0 but this is not ideal.  Is there any reason not to support Ruby 2.0.0 other then Ruby 2.0.0 is EOL?

**Comment by gildub** [comment]
@sleepyorion, yes that's pretty much the reason, because the windows is moving forward and everything else is following up.

Conversely it creates too many paths to follow-up with. So usually an older version, in this instance a former fog-openstack version supporting Ruby < 2.1, would be used to satisfy the constraint, which means not being able to benefit from any changes unless back-ported which is usually happening only for security patches.

The best way to address this is to push for OneOps to start moving toward Ruby >= 2.1.

Creating a branch kind of give you a way in between but doesn't help on the long run, I would strongly recommend to start pushing for Ruby >= 2.1 support, anybody fighting back would be wrong.

**Comment by gildub** [comment]
Although the aforementioned solution is recommended alternatively you could fork and hack the issues after downgrading to 2.0.0. 

Anyway, closing this one, please re-opened if needed.
