### ISSUE TITLE
version 0.3.5 API changes

### ISSUE THREAD

**Issue by ideaship** [fog/fog-openstack#449]
With version 0.3.5, chef-client tests that used to work with 0.3.4 are broken. In contrast to 0.3.1, it is not the interface names that changed but what they do.

We end up with identity endpoints such as http://127.0.0.1:35357/v3/auth/tokens/v3/auth/tokens.

fog-openstack has been reliable for us for a long time, but the past months have been a rather bumpy ride.

**Comment by jbartko** [comment]
Having to repeatedly rewrite integration testing harnesses to correctly interpolate the OS_AUTH_URL endpoint has been at the very least annoying.

Prior to fog-openstack 0.2.0, this worked with kitchen-openstack:
```
"#{ENV['OS_AUTH_URL']}/auth/tokens"
```
Now this appears to be working well (at least in my environment):
```
ENV['OS_AUTH_URL'].gsub(/\/v[23].*$/, '')
```
Except for the case of fog-openstack 0.3.1, which may be related to test-kitchen/kitchen-openstack#189.

**Comment by gildub** [comment]
Latest release 0.3.6 containing the following patch should help https://github.com/fog/fog-openstack/pull/450

@ideaship, the last couple of months have effectively seen lots of changes in order to adjust to fog-core 2+ and also to refactor the authentication bootstrapping, all done by a very limited number of maintainers ;)
