### ISSUE TITLE
Cannot Get Openstack Identity v3 Calls Working

### ISSUE THREAD

**Issue by plribeiro3000** [fog/fog-openstack#54]
I am trying to use identity v3, but it defaults back to v2. We pass in the /v3/auth/tokens URL and it authenticates correctly, but all calls go to the older v2 URL. During debugging, we turned on EXCON_DEBUG and noticed the code is switching to v2 based on the endpoints provided in server response. In the response there is no v3 endpoints. In the v2 code, @openstack_management_url is set to use the authentication URL as a base, which seems to drive future calls to v2 resources. Is there anything we need to do to get v3 identity to work properly?

Original issue opened by @j-bailey at fog/fog#3758

**Comment by plribeiro3000** [comment]
cc/ @j-bailey @dhague @seanhandley @MaPoCaCe

**Comment by dhague** [comment]
Sorry for the late response. It sounds like your OpenStack Keystone does not have a v3 Identity service & endpoints configured - the service may be there, but Keystone doesn't know about it. Hence, it's not returned in the service catalog and Fog doesn't see it either.

**Comment by Ladas** [comment]
yeah you need keystonev3 in the endpoint list

**Comment by peterklipfel** [comment]
I'm having a very similar issue. However, when I explicitly use the v2.0 endpoint, it still tries to use /v3.

That is:

```ruby
{openstack_auth_url: "http://IP:5000/v2.0/tokens", :openstack_username=>"username", :openstack_api_key=>"password" }
identity = Fog::Identity::OpenStack::V2.new(@identity_connection_params)
identity.tenants # <= this makes a request to /v3/tenants
```

**Comment by peterklipfel** [comment]
@dhague @Ladas Additionally, keystone lists the endpoint in an accessible place. I can use curl requests to perform the actions. All identity related requests, except the instantiation, are timing out

**Comment by gildub** [comment]
Just to clarify (including myself as I'm trying to understand what's going on):

- Starting with Liberty, Keystone engine itself is `version 3` by default:
`OS_AUTH_URL=http://host.example.com:5000` and by providing the required domain.

- API version 2 is also available for backward compatibility, in which case it must explicitly used: (OS_AUTH_URL=http://host.example.com:5000/v2.0)

Outside of fog, since Keystone is v3 by default, the service/endpoints don't even have to advertised to be usable. For instance, in my current Liberty lab (RHOS 8 - OSP-director), the v2 service/endpoints are set up by default but not the v3 endpoint, I can still use either v2 or v3 authentication methods.

When using fog/fog-openstack,  the catalog(service/endpoints) helps determine which service can be offered. 

So in my lab case above, where v2 catalog is defined and not v3, I always end up using v2 even though I specify `:openstack_auth_url => "http://host.example.com:5000/v3/auth/tokens"` I get a v2 object: `Fog::Identity::OpenStack::V2::Real`

Now after adding the identityv3 service/endpoint I still cannot create a v3 object:

```
$ openstack service list
+----------------------------------+------------+---------------+
| ID                               | Name       | Type          |
+----------------------------------+------------+---------------+
| 0112b2dd58a34a4f8c6a44eec7759f32 | novav3     | computev3     |
| 033fec3f8c1e4da19d25e52317d45119 | nova       | compute       |
| 1a37726f014a4708b0b8781190dab028 | keystonev3 | identityv3    |
| 2c30aafc41cf496c8e1ebdd02aa57200 | keystone   | identity      |
| 4eecb66e00194e81971343c4172c7b2e | swift      | object-store  |
| 5b93bee4eabf43d78c6f187bde3db44d | heat       | orchestration |
| 7458d5ed287c4c189975a3aaba5d3d23 | glance     | image         |
| 9cf8c910f6a94a7ca09ce42d39474a6c | ironic     | baremetal     |
| a7a3ef724f0e45a8ad1ea97aa4d0bf39 | aodh       | alarming      |
| ba24ad3770104b5ebe587a968e856058 | neutron    | network       |
| fccfe931548c4a54ac81cf752fd36044 | ceilometer | metering      |
+----------------------------------+------------+---------------+

$ openstack endpoint list | grep keystonev3
| 1670883cb2a4425b878f5549b243d1b6 | regionOne | keystonev3   | identityv3    | True    | internal  | http://192.0.2.1:5000                       |
| 16d955bb3449458fbcdf2d33ab51a693 | regionOne | keystonev3   | identityv3    | True    | public    | http://192.0.2.1:5000                       |
| 971bb8a3d5314c9aa7f71145a27e67c4 | regionOne | keystonev3   | identityv3    | True    | admin     | http://192.0.2.1:5000                       |
```

```ruby
identity = Fog::Identity::OpenStack::V3.new(@connection_params)
Fog::Errors::NotFound: Could not find service identity_v3, identityv3, identity. Have alarming, baremetal, compute, computev3, identity, identityv3, image, metering, network, object-store, orchestration
```

Another issue, for the default identity class to be V3, the path is searched for 'v3' in he path, which could  is not necessarily always the case. Since Keystone v3 is the default it doesn't have to contain v3 although it could.

I'm investigating further....

**Comment by gildub** [comment]
For fog-openstack to work with Keystone v3 it requires keystonev3 endpoints to be defined with the version in the url, such as: 
```
openstack endpoint list | grep keystonev3
| 4716e166e4e447fab36c3d0f012dce06 | regionOne | keystonev3   | identityv3    | True    | admin     | http://192.0.2.1:35357/v3                   |
| 519aff83d1084f17b8d25b3a65bd9c66 | regionOne | keystonev3   | identityv3    | True    | internal  | http://192.0.2.1:5000/v3                    |
| 9bef5c84679b4583a9aca309dd990ea8 | regionOne | keystonev3   | identityv3    | True    | public    | http://192.0.2.1:5000/v3                    |
```

@plribeiro3000, can you please confirm with above?
@peterklipfel , I'm not following you, could please develop?

**Comment by seanhandley** [comment]
I hit this problem a while back.

Current workaround is:

`:openstack_identity_prefix => 'v3'`

Passing this param to Fog will have it prepend the URL with the identity prefix "v3". This allows your catalog to serve URLs that don't have version information hardcoded in them (i.e. if you want to run Keystone v2 and v3 side by side).

**Comment by gildub** [comment]
@seanhandley, the `:openstack_identity_prefix` param does effectively prefix the path.
Meanwhile that doesn't help, at least for me, as autodetect somehow ends up with `:path => "/v3//v2.0/users"`! 

I think this is harder than it should be. I believe identity could afford a refactor in order to go version-less by default, which is the standard with Keystone v3 and at same time still be able to use v2 if needed just by providing auth_url for v2. That would allow to use v3 out of the box without any changes on Openstack side (like adding v3 service/endpoints).

**Comment by seanhandley** [comment]
Oh yes, I think I had to use it in conjunction with `:openstack_endpoint_path_matches => //`.

Agree, it's well overdue a rewrite.

**Comment by achevalet** [comment]
Pull request #268 should help

**Comment by gildub** [comment]
Thanks @achevalet
